### ISSUE TITLE
Revit git error

### ISSUE THREAD

**Issue by mkadonoff** [vnoves/BIMSocket#2]
Cloning into 'C:/Users/mkadonoff/source/repos/BIMSocket/Revit/RvtVa3c'...
Remote: Enumerating objects: 4, done.        
Remote: Counting objects:  25% (1/4)        
Remote: Counting objects:  50% (2/4)        
Remote: Counting objects:  75% (3/4)        
Remote: Counting objects: 100% (4/4)        
Remote: Counting objects: 100% (4/4), done.        
Remote: Compressing objects:  25% (1/4)        
Remote: Compressing objects:  50% (2/4)        
Remote: Compressing objects:  75% (3/4)        
Remote: Compressing objects: 100% (4/4)        
Remote: Compressing objects: 100% (4/4), done.        
Remote: Total 785 (delta 0), reused 3 (delta 0), pack-reused 781        
Error encountered while cloning the remote repository: Git failed with a fatal error.
remote error: upload-pack: not our ref 2e2d0d3b957025dd3f643a203a90de3dcfa5b6a3e-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed allow-tip-sha1-in-want allow-reachable-sha1-in-want no-done symref=HEAD:refs/heads/gh-pages filter agent=git/github-g635995a8d099
the remote end hung up unexpectedly
Fetched in submodule path 'Revit/RvtVa3c', but it did not contain 2e2d0d3b957025dd3f643a203a90de3dcfa5b6a3. Direct fetching of that commit failed.

**Comment by pabloderen** [comment]
Can't reproduce, please be sure you are updating the modules only after cloning the main project

git clone https://github.com/vnoves/BIMSocket.git
git pull --recurse-submodules
git submodule update --init --recursive
git submodule update --recursive --remote

**Comment by mkadonoff** [comment]
Pablo - Thanks for your help.

I deleted and recreated the repo - still running into the same error with Revit/RvtVa3c

$ git clone https://github.com/vnoves/BIMSocket.git
Cloning into 'BIMSocket'...
remote: Enumerating objects: 107, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 5247 (delta 26), reused 65 (delta 11), pack-reused 5140
Receiving objects: 100% (5247/5247), 213.40 MiB | 9.42 MiB/s, done.
Resolving deltas: 100% (2172/2172), done.

$ cd BIMSocket
$ git pull --recurse-submodules
Already up to date.

$ git submodule update --init --recursive
Submodule 'BIMSOCKetViewer' (https://github.com/vnoves/BIMSOCKetViewer.git) registered for path 'BIMSOCKetViewer'
Submodule 'Revit/RvtVa3c' (https://github.com/pabloderen/RvtVa3c.git) registered for path 'Revit/RvtVa3c'
Submodule 'Rhino/BIMSocket/RCvA3C' (https://github.com/pabloderen/RCvA3C.git) registered for path 'Rhino/BIMSocket/RCvA3C'
Submodule 'Rhino/BIMSocket/RhinoToJson' (https://github.com/pabloderen/RhinoToJson.git) registered for path 'Rhino/BIMSocket/RhinoToJson'
Cloning into 'C:/Users/mkadonoff/source/repos/BIMSocket/BIMSOCKetViewer'...
Cloning into 'C:/Users/mkadonoff/source/repos/BIMSocket/Revit/RvtVa3c'...
Cloning into 'C:/Users/mkadonoff/source/repos/BIMSocket/Rhino/BIMSocket/RCvA3C'...
Cloning into 'C:/Users/mkadonoff/source/repos/BIMSocket/Rhino/BIMSocket/RhinoToJson'...
Submodule path 'BIMSOCKetViewer': checked out 'e641b6db07b92c7a9ce23ad7ba83b98ef2e2bf6c'
fatal: remote error: upload-pack: not our ref 2e2d0d3b957025dd3f643a203a90de3dcfa5b6a3
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'Revit/RvtVa3c', but it did not contain 2e2d0d3b957025dd3f643a203a90de3dcfa5b6a3. Direct fetching of that commit failed.

$ git submodule update --recursive --remote
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'Revit/RvtVa3c'

**Comment by pabloderen** [comment]
I was able to reproduce the bug and I think I fixit. 

There was a problem in the Revit/RvtVa3c submodule origin. Could you please try one more time? This is how it looks on my terminal.

![imagen](https://user-images.githubusercontent.com/14131475/88361866-e9b12580-cd50-11ea-8d08-d28f8fb31c01.png)

**Comment by mkadonoff** [comment]
Looks like this issue is resolved - 

$ git clone https://github.com/vnoves/BIMSocket.git
Cloning into 'BIMSocket'...
remote: Enumerating objects: 179, done.
remote: Counting objects: 100% (179/179), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 5319 (delta 66), reused 120 (delta 39), pack-reused 5140
Receiving objects: 100% (5319/5319), 213.45 MiB | 26.86 MiB/s, done.
Resolving deltas: 100% (2212/2212), done.

$ git pull --recurse-submodules
Already up to date.

$ git submodule update --init --recursive
Submodule 'BIMSOCKetViewer' (https://github.com/vnoves/BIMSOCKetViewer.git) registered for path 'BIMSOCKetViewer'
Submodule 'Revit/RvtVa3c' (https://github.com/pabloderen/RvtVa3c.git) registered for path 'Revit/RvtVa3c'
Submodule 'Rhino/BIMSocket/RCvA3C' (https://github.com/pabloderen/RCvA3C.git) registered for path 'Rhino/BIMSocket/RCvA3C'
Submodule 'VIM/vim-desktop-sdk' (https://github.com/pabloderen/vim-desktop-sdk.git) registered for path 'VIM/vim-desktop-sdk'
Cloning into 'C:/Users/mkadonoff/source/repos/bimsocket/BIMSOCKetViewer'...
Cloning into 'C:/Users/mkadonoff/source/repos/bimsocket/Revit/RvtVa3c'...
Cloning into 'C:/Users/mkadonoff/source/repos/bimsocket/Rhino/BIMSocket/RCvA3C'...
Cloning into 'C:/Users/mkadonoff/source/repos/bimsocket/VIM/vim-desktop-sdk'...
Submodule path 'BIMSOCKetViewer': checked out '9760f6308abdb2afb601884717c086b4598219ca'
Submodule path 'Revit/RvtVa3c': checked out 'a5f7c65f88edcc9d5c9a93e976c9a50ee6c11552'
Submodule path 'Rhino/BIMSocket/RCvA3C': checked out 'f8009263b5a5314be44e919f7921f24ec312eb05'
Submodule path 'VIM/vim-desktop-sdk': checked out '20174964c539ed0c87f0ac207dd71ae1a88e9c11'
